training:
  learning_rate: 1e-3
  epochs: 30
  batch_size: 64
  momentum: 0.9

data:
  train: "data/train.csv"
  test: "data/test.csv"
  validation: "data/validation.csv"
  best_model: "outputs/2025-11-14/12-37-11/best_model.pth"
